### ISSUE TITLE
Stealthburner Rapido Uhf

### ISSUE THREAD

**Issue by gogsi1** [sorted01/Filametrix#3]
do it under rapido uhf

**Comment by gogsi1** [comment]
> Sorry, I don't get it? :)

Make your mod for this version https://www.teamfdm.com/files/file/631-stealthburner-rapido-uhf/

**Comment by sorted01** [comment]
[@juliusjj25](https://github.com/juliusjj25) has created it for Rapido. Don't know if it is same as UHF. Please check the updated files and let me know.

**Comment by gogsi1** [comment]
> [@juliusjj25](https://github.com/juliusjj25) has created it for Rapido. Don't know if it is same as UHF. Please check the updated files and let me know.

Thanks, this is the Rapido HF version. It remains to be done for UHF, but here only the airflow needs to be lengthened.

**Comment by gogsi1** [comment]
![Снимок экрана 2023-06-20 210206](https://github.com/sorted01/Filametrix/assets/36478778/baa1027c-9f7b-4643-8306-af108d48fbbc)

**Comment by dridas** [comment]
I actually started modifying this yesterday for the Rapido UHF.  You actually need to modify the SBRapidi TH front cutter, to add the third hole for the pivot point.  I managed to get that done yesterday, but the cutter arm isn't long enough.  

I took the stealthburner rapido uhf and just overlaid the differences and it seems to work for that part.  I need to extend the arm above the spring so it lines up with where the blade lays down on it.  Work in progress, and will attempt to do that this evening.  

One question, has anybody thought about using N52 5x3mm opposing magnets instead of the spring?

**Comment by gogsi1** [comment]
> I actually started modifying this yesterday for the Rapido UHF. You actually need to modify the SBRapidi TH front cutter, to add the third hole for the pivot point. I managed to get that done yesterday, but the cutter arm isn't long enough.
> 
> I took the stealthburner rapido uhf and just overlaid the differences and it seems to work for that part. I need to extend the arm above the spring so it lines up with where the blade lays down on it. Work in progress, and will attempt to do that this evening.
> 
> One question, has anybody thought about using N52 5x3mm opposing magnets instead of the spring?

Hmm, good idea about the magnet. Can you make a 6x3 mm size?

**Comment by dridas** [comment]
I was inclined to use the 6x3 magnets at first, since they seem to be more common.  The cutter arm is pretty narrow, and just barely fits a 5mm magnet. On second review, it looks like I didn't make the cutout for the knife cutter on the arm, so might not have to adjust the cutter arm after all, but will need to make another print of the Rapido UHF Front Cutter. 

I'll see what I can do about the 6mm magnet. Hope to have a finished prototype by the weekend, but life might get in the way. I have lots of magnets sitting around, and even some 6x10mm's that I think would be better for the body side to provide a stronger repel of the cutter arm.  I'll start with 6x3's, and see hot that works first

**Comment by sorted01** [comment]
Good idea with the magnets. Somehow I always had the spring in mind. Thanks for modding the parts. Currently I can hardly find time. Family and stuff 😅🙈

**Comment by dridas** [comment]
Prototype printing now, with 6x3 magnets. Running it a little slow, cause I'm a little sketchy on overhangs, but give it a few hours, and hopefully I'll know if it's doable.  Got some life things to deal with in the mean time, but more to follow.

**Comment by dridas** [comment]
I can't make any gaurantees that this is 100% correct, or that it couldn't be made better. Still a work in progress, and I haven't mounted my Rapido UHF to it (yet).  

I did have to adjust the M3 heatset inserts, since they were slipping a little once I set them in place. Just the two that mate with the back of the Rapido (where the 6mm magnet goes).  If you make any modifications, I'd appreciate a message, since obviously any improvements might be good for the community. 

[https://github.com/dridas/SBRapido-UHF-Cutter](url)

also, credit to Filametrix, and this repo, and any contributors. I didn't do any of these designs myself, just made some slight modifications and blended stl's.

**Comment by gogsi1** [comment]
> I can't make any gaurantees that this is 100% correct, or that it couldn't be made better. Still a work in progress, and I haven't mounted my Rapido UHF to it (yet).
> 
> I did have to adjust the M3 heatset inserts, since they were slipping a little once I set them in place. Just the two that mate with the back of the Rapido (where the 6mm magnet goes). If you make any modifications, I'd appreciate a message, since obviously any improvements might be good for the community.
> 
> [https://github.com/dridas/SBRapido-UHF-Cutter](url)
> 
> also, credit to Filametrix, and this repo, and any contributors. I didn't do any of these designs myself, just made some slight modifications and blended stl's.

When can I download your version? I really want to try it.

**Comment by dridas** [comment]
For some reason the link didn't work.  
Try This one:

https://github.com/dridas/SBRapido-UHF-Cutter

**Comment by gogsi1** [comment]
> For some reason the link didn't work. Try This one:
> 
> https://github.com/dridas/SBRapido-UHF-Cutter

Thank you, the link is working now.

**Comment by BlackNet** [comment]
> 

Do you have any videos of the magnets in use?  Also am going to print this and see. I have been trying to make some mods for the UHF but have yet to be happy with what I have done with them.  It looks like this one should work just fine for me.
